# Generated by Django 4.2.21 on 2025-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='size_l',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='size_s',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='size_xl',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='size_xxl',
        ),
        migrations.AddField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='size',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='color',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('white', 'Trắng'), ('black', 'Đen'), ('gray', 'Xám'), ('light_gray', 'Xám nhạt'), ('dark_gray', 'Xám đậm'), ('blue', 'Xanh dương'), ('navy', 'Xanh navy / xanh than'), ('sky_blue', 'Xanh da trời'), ('green', 'Xanh lá'), ('olive', 'Xanh rêu'), ('red', 'Đỏ'), ('wine', 'Đỏ đô'), ('pink', 'Hồng'), ('light_pink', 'Hồng phấn'), ('purple', 'Tím'), ('yellow', 'Vàng'), ('beige', 'Be'), ('brown', 'Nâu'), ('cream', 'Kem'), ('orange', 'Cam')], default='Unknown', max_length=50),
        ),
    ]
