# Generated by Django 4.2.23 on 2025-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productstock_size_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='color',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('white', 'Trắng'), ('black', 'Đen'), ('gray', 'Xám'), ('light_gray', 'Xám nhạt'), ('dark_gray', 'Xám đậm'), ('blue', 'Xanh dương'), ('navy', 'Xanh navy / xanh than'), ('sky_blue', 'Xanh da trời'), ('dark_blue', 'Xanh đâm'), ('green', 'Xanh lá'), ('olive', 'Xanh rêu'), ('red', 'Đỏ'), ('wine', 'Đỏ đô'), ('pink', 'Hồng'), ('light_pink', 'Hồng phấn'), ('purple', 'Tím'), ('yellow', 'Vàng'), ('beige', 'Be'), ('brown', 'Nâu'), ('cream', 'Kem'), ('orange', 'Cam')], default='Unknown', max_length=50),
        ),
    ]
