# Generated by Django 4.2.23 on 2025-08-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.AddField(
            model_name='productstock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productstock',
            name='promotions',
            field=models.ManyToManyField(related_name='products', to='product.promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'size', 'color')},
        ),
    ]
