# Generated by Django 4.2.23 on 2025-08-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_price_remove_product_promotions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.promotion'),
        ),
    ]
