# Generated by Django 4.2.23 on 2025-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productstock_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
